# Generated by Django 4.2.19 on 2025-02-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='User',
        ),
    ]
